name: build Azul Zulu
on:
  push:
    branches:
      - master
    paths:
      - java/zulu/**
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"

    strategy:
      fail-fast: false

      matrix:
        image:

          # Azul Zulu OpenJDK
          - {name: "8-zulu", image: "8", platforms: "linux/amd64,linux/arm64"}
          - {name: "11-zulu", image: "11", platforms: "linux/amd64,linux/arm64"}
          - {name: "17-zulu", image: "17", platforms: "linux/amd64,linux/arm64"}
          - {name: "21-zulu", image: "21", platforms: "linux/amd64,linux/arm64"}
          - {name: "22-zulu", image: "22", platforms: "linux/amd64,linux/arm64"}
          - {name: "23-zulu", image: "23", platforms: "linux/amd64,linux/arm64"}

          # Azul Zulu CRaC
          - {name: "17-zulu-crac", image: "17-CRaC", platforms: "linux/amd64,linux/arm64"}
          - {name: "21-zulu-crac", image: "21-CRaC", platforms: "linux/amd64,linux/arm64"}
          - {name: "22-zulu-crac", image: "22-CRaC", platforms: "linux/amd64,linux/arm64"}
          - {name: "23-zulu-crac", image: "23-CRaC", platforms: "linux/amd64,linux/arm64"}


    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ matrix.image.platforms != 'linux/amd64' }}

      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./java/zulu
          file: ./java/zulu/${{ matrix.image.image }}/Dockerfile
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: |
            ghcr.io/rafi67000/images:zulu${{ matrix.image.image }}
